# ============================================================================
# 🏆 ULTIMATE MAXIMUM POWER TRADING ALGORITHM 🏆
# ============================================================================
# Beyond institutional grade - incorporating techniques from:
# - XTX Markets (market making)
# - Jump Trading (HFT)
# - Citadel (quant strategies)
# - Renaissance Technologies (statistical arbitrage)
# ============================================================================

seed: 42

# ============================================================================
# DATA - MAXIMUM DEPTH
# ============================================================================
data:
  primary_pair: "BTCUSDT"
  
  # Multi-asset portfolio
  portfolio_pairs:
    - "ETHUSDT"
    - "BNBUSDT"
    - "SOLUSDT"
    - "ADAUSDT"
    - "XRPUSDT"
  
  # Correlation pairs for cross-asset features
  correlation_pairs:
    - "ETHUSDT"
    - "BNBUSDT"
  
  # Multi-timeframe (tick to daily)
  timeframes:
    primary: "1m"
    analysis: ["1m", "5m", "15m", "1h", "4h", "1d"]
  
  history_days: 180  # 6 months for robust learning
  
  # Order book depth
  orderbook:
    depth: 100  # Top 100 levels (institutional grade)
    update_frequency: "1s"  # Real-time updates
    features:
      - "full_depth_imbalance"
      - "order_flow_toxicity"
      - "liquidity_score"
      - "hidden_liquidity_proxy"
      - "order_arrival_rate"
      - "quote_intensity"
  
  # On-chain metrics (crypto-specific alpha)
  onchain:
    enabled: true
    metrics:
      - "exchange_inflow"
      - "exchange_outflow"
      - "whale_transactions"
      - "active_addresses"
      - "network_value"
      - "nvt_ratio"  # Network Value to Transactions
      - "mvrv_ratio"  # Market Value to Realized Value
  
  # Alternative data
  alternative:
    funding_rates: true  # Perpetual futures funding
    open_interest: true  # Derivatives OI
    liquidations: true   # Liquidation data
    social_sentiment: false  # Requires API
    news_sentiment: false    # Requires API
  
  cache_dir: "data/raw"
  processed_dir: "data/processed"

# ============================================================================
# ADVANCED FEATURE ENGINEERING
# ============================================================================
features:
  # Price microstructure (tick-level)
  microstructure:
    - "effective_spread"
    - "realized_spread"
    - "price_impact_kyle"  # Kyle's lambda
    - "amihud_illiquidity"
    - "roll_measure"
    - "high_low_estimator"  # Corwin-Schultz
    - "bid_ask_bounce"
    - "trade_direction_intensity"
  
  # Order flow (Level 2/3)
  order_flow:
    - "order_book_imbalance_deep"  # All 100 levels
    - "order_size_distribution"
    - "large_order_detection"  # Whale detection
    - "order_cancellation_rate"
    - "order_flow_toxicity_vpin"  # Volume-Synchronized PIN
    - "trade_aggression_score"
  
  # Liquidity
  liquidity:
    - "bid_ask_spread_multiple_levels"
    - "depth_at_best"
    - "cumulative_depth_curve"
    - "liquidity_provision_score"
    - "market_depth_resilience"
  
  # Volatility (advanced)
  volatility:
    - "parkinson"
    - "garman_klass"
    - "rogers_satchell"
    - "yang_zhang"  # Most efficient estimator
    - "realized_volatility_5m"
    - "jump_variation"  # Detect jumps
    - "volatility_of_volatility"
  
  # Volume analysis
  volume:
    - "vwap_multiple_windows"
    - "volume_profile_poc"  # Point of Control
    - "volume_imbalance_ratio"
    - "volume_weighted_pressure"
    - "money_flow_index_advanced"
  
  # Time-series momentum
  momentum:
    - "tsm_1h"  # Time-series momentum
    - "tsm_4h"
    - "tsm_1d"
    - "momentum_quality_score"
    - "trend_strength_composite"
  
  # Cross-sectional (relative strength)
  cross_sectional:
    enabled: true
    universe: ["BTC", "ETH", "BNB", "SOL", "ADA", "XRP"]
    metrics:
      - "relative_strength"
      - "correlation_matrix"
      - "cointegration_pairs"
      - "beta_to_market"
  
  # Factor models
  factors:
    - "momentum_factor"
    - "value_factor"  # NVT, MVRV
    - "size_factor"   # Market cap
    - "volatility_factor"
    - "liquidity_factor"
  
  # Regime detection (advanced)
  regime:
    methods:
      - "hmm"  # Hidden Markov Model
      - "gmm"  # Gaussian Mixture Model
      - "clustering_dynamic"
    states: 5  # Bull, Bear, Consolidation, Volatile, Crash
    use_regime_specific_models: true

# ============================================================================
# TARGET CONFIGURATION
# ============================================================================
target:
  primary_horizon: 5  # 5-minute forward return
  horizons: [5, 10, 15]  # Multi-horizon targets
  up_threshold: 0.002  # +0.2% for up label
  down_threshold: -0.002  # -0.2% for down label
  balance_classes: true
  balancing_method: "downsample"  # or "weights"

# ============================================================================
# ADVANCED ML MODELS
# ============================================================================
models:
  # Ensemble of ensembles
  meta_ensemble:
    enabled: true
    method: "stacking"  # Stack multiple ensembles
    
  # Gradient Boosting (optimized)
  lightgbm:
    n_estimators: 1000
    learning_rate: 0.01
    max_depth: 12
    num_leaves: 255
    min_child_samples: 50
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 1.0
    boosting_type: "gbdt"
    objective: "binary"
    metric: "auc"
  
  xgboost:
    n_estimators: 1000
    learning_rate: 0.01
    max_depth: 12
    min_child_weight: 3
    subsample: 0.8
    colsample_bytree: 0.8
    gamma: 0.1
    reg_alpha: 0.1
    reg_lambda: 1.0
  
  catboost:
    iterations: 1000
    learning_rate: 0.01
    depth: 12
    l2_leaf_reg: 3.0
  
  # Transformer (attention-based)
  transformer:
    enabled: true
    d_model: 256
    nhead: 8
    num_layers: 6
    dim_feedforward: 1024
    dropout: 0.2
    sequence_length: 60  # 1 hour context
    use_positional_encoding: true
    use_multi_head_attention: true
  
  # LSTM with attention
  lstm_attention:
    enabled: true
    hidden_size: 256
    num_layers: 3
    bidirectional: true
    attention_heads: 8
    dropout: 0.3
  
  # Reinforcement Learning (DQN)
  reinforcement:
    enabled: true
    algorithm: "PPO"  # Proximal Policy Optimization
    reward_function: "sharpe"  # Optimize Sharpe directly
    action_space: ["buy", "sell", "hold", "buy_strong", "sell_strong"]
    state_features: "all"
    discount_factor: 0.99
    learning_rate: 0.0001
  
  # Meta-learning (MAML)
  meta_learning:
    enabled: true
    algorithm: "MAML"  # Model-Agnostic Meta-Learning
    inner_lr: 0.01
    outer_lr: 0.001
    adaptation_steps: 5
    meta_batch_size: 16
  
  # Adversarial training
  adversarial:
    enabled: true
    epsilon: 0.01  # Perturbation magnitude
    method: "FGSM"  # Fast Gradient Sign Method
    robustness_weight: 0.1

# ============================================================================
# ADVANCED RISK MANAGEMENT
# ============================================================================
risk:
  initial_capital: 10000
  
  # Portfolio optimization
  portfolio_optimization:
    method: "black_litterman"  # or "mean_variance", "risk_parity"
    rebalance_frequency: "daily"
    constraints:
      max_weight_per_asset: 0.30
      min_weight_per_asset: 0.05
      max_sector_exposure: 0.50
  
  # Dynamic position sizing
  position_sizing:
    method: "kelly_fractional"
    kelly_fraction: 0.25
    max_position: 0.25
    confidence_multiplier: true
    volatility_adjusted: true
  
  # Risk limits (advanced)
  limits:
    max_portfolio_var: 0.02  # 2% daily VaR
    max_cvar: 0.03  # 3% Conditional VaR
    max_portfolio_heat: 0.06
    max_correlation_exposure: 0.4
    max_drawdown: 0.15
    max_daily_loss: 0.02
    max_leverage: 1.0  # No leverage for crypto spot
  
  # Stop-loss (dynamic)
  stops:
    method: "atr_based"  # ATR-based stops
    atr_multiplier: 2.0
    trailing_stop: true
    trailing_activation: 0.015  # Start trailing at 1.5%
    trailing_distance: 0.005    # Trail by 0.5%
  
  # Take-profit (dynamic)
  targets:
    method: "risk_reward"
    min_risk_reward: 2.0  # Min 2:1 reward/risk
    scale_out: true  # Take partial profits
    scale_levels: [0.5, 0.75, 1.0]  # At 50%, 75%, 100% of target
  
  # Stress testing
  stress_tests:
    enabled: true
    scenarios:
      - "flash_crash"
      - "liquidity_crisis"
      - "black_swan"
      - "correlation_breakdown"
    frequency: "daily"

# ============================================================================
# ADVANCED EXECUTION
# ============================================================================
execution:
  # Smart order routing
  routing:
    enabled: true
    exchanges: ["binance", "coinbase", "kraken"]
    route_method: "best_execution"  # Price + liquidity + fees
  
  # Algo execution
  algorithms:
    - name: "TWAP"  # Time-Weighted Average Price
      enabled: true
      duration: 300  # 5 minutes
    - name: "VWAP"  # Volume-Weighted Average Price
      enabled: true
      participation_rate: 0.1  # 10% of volume
    - name: "POV"   # Percentage of Volume
      enabled: true
      target_percentage: 0.05
    - name: "adaptive"  # Adaptive algo
      enabled: true
      aggressiveness: "medium"
  
  # Slippage optimization
  slippage:
    model: "market_impact_kyle"
    max_acceptable: 0.002  # 0.2%
    adaptive_sizing: true
  
  # Latency optimization
  latency:
    target_ms: 100  # 100ms target
    colocation: true  # ✅ ENABLED - Co-location ready
    network_optimization: true
    # --- Low latency extensions (added) ---
    enable_low_latency: true         # ✅ ENABLED - Microsecond execution active
    microseconds_target: 1000         # Target p99 latency in microseconds
    time_sync: "ptp"                  # ptp | ntp (PTP = Precision Time Protocol)
    venue: "binance"
    clock_source: "steady_clock"      # reference clock for stamps

# ============================================================================
# ONLINE LEARNING & ADAPTATION
# ============================================================================
online_learning:
  enabled: true
  method: "incremental"  # or "sliding_window"
  
  # Update frequency
  update:
    frequency: "hourly"
    min_new_samples: 60
    learning_rate_decay: 0.99
  
  # Concept drift detection
  drift_detection:
    enabled: true
    method: "ADWIN"  # Adaptive Windowing
    alert_threshold: 0.002
    action_on_drift: "retrain"
  
  # Active learning
  active_learning:
    enabled: true
    query_strategy: "uncertainty"
    label_budget: 100  # per day

# ============================================================================
# BACKTESTING (realistic)
# ============================================================================
backtest:
  # Realism settings
  slippage_model: "quadratic"  # Realistic market impact
  transaction_costs: 0.001
  market_impact: true
  partial_fills: true
  
  # Walk-forward optimization
  walk_forward:
    enabled: true
    train_days: 90
    test_days: 7
    step_days: 7
    anchored: false  # Rolling window
  
  # Monte Carlo
  monte_carlo:
    enabled: true
    n_simulations: 10000
    confidence_levels: [0.95, 0.99]
  
  # Metrics
  metrics:
    primary: "sharpe_ratio"
    secondary: ["sortino", "calmar", "omega", "information_ratio"]

# ============================================================================
# MONITORING & OPTIMIZATION
# ============================================================================
monitoring:
  # Real-time metrics
  track_realtime:
    - "pnl"
    - "sharpe"
    - "drawdown"
    - "hit_rate"
    - "profit_factor"
    - "kelly_criterion_score"
    - "market_regime"
  
  # Alerts
  alerts:
    telegram: false
    discord: false
    email: false
    webhook: false
  
  # Dashboards
  dashboard:
    enabled: true
    refresh_rate: 1  # seconds
    charts:
      - "equity_curve"
      - "drawdown"
      - "feature_importance"
      - "regime_distribution"
      - "order_flow"
  
  # Logging
  logging:
    level: "INFO"
    track_predictions: true
    track_features: true
    track_regime: true
    database: "sqlite"  # or "postgresql"

# ============================================================================
# HYPERPARAMETER OPTIMIZATION
# ============================================================================
optimization:
  method: "bayesian"  # Bayesian optimization
  objective: "sharpe_ratio"
  n_trials: 1000
  n_jobs: -1  # Use all cores
  
  search_space:
    learning_rate: [0.001, 0.1, "log"]
    max_depth: [6, 15, "int"]
    confidence_threshold: [0.55, 0.85, "float"]
    kelly_fraction: [0.1, 0.5, "float"]
  
  cross_validation:
    method: "purged_kfold"  # Time-series aware
    n_splits: 5
    embargo: 0.01  # 1% embargo period

# ============================================================================
# ADVANCED FEATURES
# ============================================================================
advanced:
  # Multi-objective optimization
  multi_objective:
    enabled: true
    objectives:
      - "maximize_return"
      - "minimize_risk"
      - "maximize_sharpe"
    method: "pareto_frontier"
  
  # Transfer learning
  transfer_learning:
    enabled: true
    source_assets: ["stocks", "forex"]  # Learn from other markets
    freeze_layers: [0, 1, 2]  # Freeze early layers
  
  # Ensemble diversity
  ensemble_diversity:
    enforce: true
    min_diversity: 0.3
    methods: ["bagging", "boosting", "stacking"]
  
  # Feature selection (dynamic)
  feature_selection:
    method: "boruta"  # or "shap", "permutation"
    n_features: "auto"
    update_frequency: "weekly"
  
  # Explainability
  explainability:
    enabled: true
    methods: ["shap", "lime", "attention_weights"]
    generate_reports: true

